### ISSUE TITLE
InvalidSchema("No connection adapters were found for {!r}"

### ISSUE THREAD

**Issue by dazzzl** [tillsteinbach/VWsFriend#126]
last night, I had the following issue. After that, there was no sync with the weconnect server anymore

```
2021-12-16T02:00:32+0100:INFO:vwsfriend_base:Updating data from WeConnect
2021-12-16T02:05:32+0100:INFO:vwsfriend_base:Updating data from WeConnect
2021-12-16T02:05:36+0100:INFO:weconnect:Token refreshed
2021-12-16T02:10:32+0100:INFO:vwsfriend_base:Updating data from WeConnect
2021-12-16T02:15:32+0100:INFO:vwsfriend_base:Updating data from WeConnect
2021-12-16T02:20:32+0100:INFO:vwsfriend_base:Updating data from WeConnect
2021-12-16T02:25:32+0100:INFO:vwsfriend_base:Updating data from WeConnect
2021-12-16T02:30:32+0100:INFO:vwsfriend_base:Updating data from WeConnect
2021-12-16T02:35:32+0100:INFO:vwsfriend_base:Updating data from WeConnect
2021-12-16T02:51:46+0100:WARNING:connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='mobileapi.apps.emea.vwapps.io', port=443): Read timed out. (read timeout=None)")': /vehicles
2021-12-16T02:55:37+0100:INFO:weconnect:Token refreshed
2021-12-16T03:08:03+0100:WARNING:connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='vehicle-images-service.apps.emea.vwapps.io', port=443): Read timed out. (read timeout=None)")': /v2/vehicle-images/WVWZZZEXXXXXXXXX?resolution=2x
2021-12-16T03:08:03+0100:INFO:vehicle:Server asks for new authorization
Traceback (most recent call last):
  File "/usr/local/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/vwsfriend/vwsfriend_base.py", line 201, in main
    weConnect.update(updateCapabilities=True, updatePictures=True, force=True)
  File "/usr/local/lib/python3.8/site-packages/weconnect/weconnect.py", line 527, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force)
  File "/usr/local/lib/python3.8/site-packages/weconnect/weconnect.py", line 597, in updateVehicles
    self.__vehicles[vin].update(fromDict=vehicleDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures)
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements/vehicle.py", line 210, in update
    self.updatePictures()
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements/vehicle.py", line 498, in updatePictures
    self.weConnect.login()
  File "/usr/local/lib/python3.8/site-packages/weconnect/weconnect.py", line 280, in login
    loginResponse: requests.Response = self.__session.get(loginUrl, headers=self.DEFAULT_OPTIONS['loginHeaders'], allow_redirects=True)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'weconnect://authenticated#state=97d17c37b3b9bfbce5ca52c39a9f693887cb6e66faeb76b4d4b4e7cc77b3bf25&code=<removed code>&token_type=bearer&id_token=<removed token>'
2021-12-16T03:45:37+0100:INFO:weconnect:Token refreshed
2021-12-16T04:35:42+0100:INFO:weconnect:Token refreshed
2021-12-16T05:25:43+0100:INFO:weconnect:Token refreshed
```

**Comment by tillsteinbach** [comment]
I'll try to find out what was wrong here. What should work is just restarting the software.

**Comment by dazzzl** [comment]
yes, I have done this and it works again. However, it would be nice that this will be automatically resolved. Thanks for help!

**Comment by tillsteinbach** [comment]
My feeling is that your internet connection might have been down. But of course this should not happen

**Comment by dazzzl** [comment]
Could be, in the night there is the forced DSL reconnect with new IP as usual in Germany ;-)

**Comment by tillsteinbach** [comment]
I think I have a fix. Will test it for some time and then release it

**Comment by tillsteinbach** [comment]
This should be fixed
