### ISSUE TITLE
AC charging log issues. ID.4 77kWh car software version 2.3.

### ISSUE THREAD

**Issue by MattiJarvinen** [tillsteinbach/VWsFriend#261]
For some reason charging log entry failed.

Log messages
```
2022-06-22T14:21:46+0000:INFO:vwsfriend_base:Updating data from WeConnect

2022-06-22T14:21:47+0000:WARNING:generic_status:/vehicles/WVGZZZXXXXXXXXXXX/domains/charging/chargingSettings: Unknown attribute autoUnlockPlugWhenChargedAC with value off

2022-06-22T14:21:47+0000:WARNING:generic_status:/vehicles/WVGZZZXXXXXXXXXXX/domains/charging/plugStatus: Unknown attribute externalPower with value active

2022-06-22T14:21:47+0000:WARNING:generic_status:/vehicles/WVGZZZXXXXXXXXXXX/domains/charging/plugStatus: Unknown attribute ledColor with value green

Traceback (most recent call last):

  File "/opt/venv/bin/vwsfriend", line 8, in <module>

    sys.exit(main())

  File "/opt/venv/lib/python3.9/site-packages/vwsfriend/vwsfriend_base.py", line 276, in main

    weConnect.update(updateCapabilities=True, updatePictures=True, force=True)

  File "/opt/venv/lib/python3.9/site-packages/weconnect/weconnect.py", line 177, in update

    self.updateComplete()

  File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete

    child.updateComplete()

  File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete

    child.updateComplete()

  File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete

    child.updateComplete()

  [Previous line repeated 3 more times]

  File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 96, in updateComplete

    observer(element=self, flags=self.onCompleteNotifyFlags)

  File "/opt/venv/lib/python3.9/site-packages/vwsfriend/agents/charge_agent.py", line 103, in __onChargingStateChange

    if self.chargingSession is None or self.chargingSession.isClosed():

  File "/opt/venv/lib/python3.9/site-packages/vwsfriend/model/charging_session.py", line 77, in isClosed

    return self.ended is not None or self.unlocked is not None or self.disconnected is not None

  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 481, in __get__

    return self.impl.get(state, dict_)

  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 941, in get

    value = self._fire_loader_callables(state, key, passive)

  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 972, in _fire_loader_callables

    return state._load_expired(state, passive)

  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 710, in _load_expired

    self.manager.expired_attribute_loader(self, toload, passive)

  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1465, in load_scalar_attributes

    raise orm_exc.ObjectDeletedError(state)

sqlalchemy.orm.exc.ObjectDeletedError: Instance '<ChargingSession at 0x7f0f974ced30>' has been deleted, or its row is otherwise not present.
```

**Comment by tillsteinbach** [comment]
Can you check if you are running on the latest version 0.19.1 ?

**Comment by MattiJarvinen** [comment]
Apparently VWsFriend is still at 0.16.6. Will update and report back.

**Comment by MattiJarvinen** [comment]
It works. No issues.
