### ISSUE TITLE
VWsfriend won't start

### ISSUE THREAD

**Issue by matthewbyrne** [tillsteinbach/VWsFriend#306]
Noticed that 2 weeks ago VWsfriend stopped reporting data. I pulled the latest (20.1), but VWsFriend won't start up.

```
vwsfriend_1   | 2022-08-06T07:20:09+0000:INFO:vwsfriend_base:vwsfriend 0.20.1 (using WeConnect-python 0.46.0, WeConnect-mqtt 0.38.3)
vwsfriend_1   | 2022-08-06T07:20:09+0000:INFO:session_manager:Could not use token from file /tmp/weconnect.token ([Errno 2] No such file or directory: '/tmp/weconnect.token')
vwsfriend_1   | 2022-08-06T07:20:11+0000:INFO:agent_connector:It looks like you have an existing database will check if an upgrade is necessary
vwsfriend_1   | 2022-08-06T07:20:11+0000:INFO:migration:Context impl PostgresqlImpl.
vwsfriend_1   | 2022-08-06T07:20:11+0000:INFO:migration:Will assume transactional DDL.
vwsfriend_1   | 2022-08-06T07:20:11+0000:INFO:agent_connector:Database upgrade done
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/bin/vwsfriend", line 8, in <module>
vwsfriend_1   |     sys.exit(main())
vwsfriend_1   |   File "/opt/venv/lib/python3.10/site-packages/vwsfriend/vwsfriend_base.py", line 429, in main
vwsfriend_1   |     ui.run(host=args.host, port=args.port)
vwsfriend_1   |   File "/opt/venv/lib/python3.10/site-packages/vwsfriend/ui/vwsfriend_ui.py", line 209, in run
vwsfriend_1   |     webthread.start()
vwsfriend_1   |   File "/usr/lib/python3.10/threading.py", line 928, in start
vwsfriend_1   |     _start_new_thread(self._bootstrap, ())
vwsfriend_1   | RuntimeError: can't start new thread
postgresdb_1  | 2022-08-06 07:20:12.103 UTC [103] LOG:  unexpected EOF on client connection with an open transaction
vwsfriend_vwsfriend_1 exited with code 1
```

**Comment by tillsteinbach** [comment]
Can you please check which docker version you are running?

**Comment by matthewbyrne** [comment]
Running `Docker version 19.03.5, build 633a0ea838`

**Comment by matthewbyrne** [comment]
Updated to latest docker version and VWsFriend loaded, but when I restarted it I get this in the logs:
```
2022-08-08T15:28:01.575702321Z 2022-08-08T15:28:01+0000:CRITICAL:vwsfriend_base:There was a problem when authenticating with WeConnect: Error during login, account test@test.de does not exist
```

**Comment by tillsteinbach** [comment]
Is your myconfig.env correctly filled out?

**Comment by tillsteinbach** [comment]
Ok, yes that docker version is quite old. That should have been the problem.

**Comment by matthewbyrne** [comment]
> Is your myconfig.env correctly filled out?

Should be. I've not changed it from when I first configured it, though it seems postgres isn't getting updates (last log shown in grafana is from the end of July). I'll see what the logs say

**Comment by matthewbyrne** [comment]
Sorted. Brought the car online and got a fresh update. Thanks for the help
