### ISSUE TITLE
An unsupported category: TIRE  was provided

### ISSUE THREAD

**Issue by MyGitIT** [tillsteinbach/VWsFriend#332]
2022-09-23T11:47:48+0200:WARNING:generic_status:/vehicles/??????????/domains/access/accessStatus: Unknown attribute doorLockStatus with value locked
2022-09-23T11:47:48+0200:WARNING:addressable:/vehicles/??????????/domains/vehicleHealthWarnings/warningLights/warningLights/warning.msgA52B/category: An unsupported category: TIRE was provided, known values are [LIGHTING, unknown category] please report this as a bug
Traceback (most recent call last):
  File "/home/pi/.local/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/vwsfriend/vwsfriend_base.py", line 493, in main
    weConnect.update(updateCapabilities=True, updatePictures=True, force=True)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 181, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 199, in updateVehicles
    vehicle = Vehicle(weConnect=self, vin=vin, parent=self.__vehicles, fromDict=vehicleDict, fixAPI=self.fixAPI,
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/elements/vehicle.py", line 124, in __init__
    self.update(fromDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures, selective=selective)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/elements/vehicle.py", line 218, in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force, selective=selective)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/elements/vehicle.py", line 330, in updateStatus
    self.domains[domain.value][key] = className(vehicle=self, parent=self.domains[domain.value], statusId=key,
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/elements/warning_lights_status.py", line 30, in __init__
    super().__init__(vehicle=vehicle, parent=parent, statusId=statusId, fromDict=fromDict, fixAPI=fixAPI)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/elements/generic_status.py", line 38, in __init__
    self.update(fromDict=fromDict)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/elements/warning_lights_status.py", line 53, in update
    self.warningLights[warningLightDict['messageId']] = WarningLightsStatus.WarningLight(fromDict=warningLightDict,
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/elements/warning_lights_status.py", line 100, in __init__
    self.update(fromDict)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/elements/warning_lights_status.py", line 113, in update
    self.priority.fromDict(fromDict, 'priority')
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/addressable.py", line 301, in fromDict
    self.setValueWithCarTime(int(fromDict[key]), lastUpdateFromCar=None, fromServer=True)
ValueError: invalid literal for int() with base 10: ''

**Comment by MyGitIT** [comment]
Funktioniert, bei mir lag es daran, dass ich VWsFriend ohne Docker benutze und die pip Version 0.21.0 von VWsFriend stimmt nicht 100% mit der Docker Version überein bezüglich Requirements und Datenbank/Dashboards... Mit weconnect 0.48.1 und ein bisschen kopieren  der Python Scripte und Dashboards läufts.
Vielen, vielen Dank!

**Comment by tillsteinbach** [comment]
Ja, aber der Fehler wäre auch in der Docker Version passiert. Daher gibt es jetzt eine 0.22.0
