### ISSUE TITLE
Internal server error in vehicle settings page

### ISSUE THREAD

**Issue by runebakjacobsen** [tillsteinbach/VWsFriend#37]
Hi! I am trying to access http://<ip>/settings/vehicle/database/<vin>, but I am receiving an internal server error. I have attached the a dump of the error

```
vwsfriend_1   | INFO:werkzeug:77.241.128.129 - - [08/Sep/2021 06:33:46] "GET /settings/vehicle/database/XXXXXXXXXXX HTTP/1.1" 500 -
vwsfriend_1   | ERROR:werkzeug:Error on request:
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 319, in run_wsgi
vwsfriend_1   |     execute(self.server.app)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 308, in execute
vwsfriend_1   |     application_iter = app(environ, start_response)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
vwsfriend_1   |     return self.wsgi_app(environ, start_response)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
vwsfriend_1   |     response = self.handle_exception(e)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
vwsfriend_1   |     response = self.full_dispatch_request()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
vwsfriend_1   |     rv = self.handle_user_exception(e)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
vwsfriend_1   |     rv = self.dispatch_request()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
vwsfriend_1   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/vwsfriend/ui/settings.py", line 88, in vehicleDBParameters
vwsfriend_1   |     if dbVehicle.settings is None:
vwsfriend_1   | AttributeError: 'NoneType' object has no attribute 'settings'
```

**Comment by tillsteinbach** [comment]
Hmmm, this is strange. The vehicle das not exist in the database. Can you send me the beginning of the logs after startup?

**Comment by runebakjacobsen** [comment]
Sure! Clean docker-compose run gives me this: 
```
Creating network "vwsfriend_backend" with the default driver
Creating network "vwsfriend_bridge" with the default driver
Creating vwsfriend_vwsfriend_1  ... done
Creating vwsfriend_postgresdb_1 ... done
Creating vwsfriend_grafana_1    ... done
Attaching to vwsfriend_postgresdb_1, vwsfriend_grafana_1, vwsfriend_vwsfriend_1
postgresdb_1  | 
postgresdb_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgresdb_1  | 
postgresdb_1  | 2021-09-08 12:32:18.136 UTC [1] LOG:  starting PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgresdb_1  | 2021-09-08 12:32:18.140 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresdb_1  | 2021-09-08 12:32:18.141 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresdb_1  | 2021-09-08 12:32:18.150 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresdb_1  | 2021-09-08 12:32:18.162 UTC [12] LOG:  database system was shut down at 2021-09-08 12:30:55 UTC
postgresdb_1  | 2021-09-08 12:32:18.183 UTC [1] LOG:  database system is ready to accept connections
grafana_1     | ✔ Downloaded natel-discrete-panel v0.1.1 zip successfully
grafana_1     | 
grafana_1     | Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
grafana_1     | 
grafana_1     | ✔ Downloaded pierosavi-imageit-panel v1.0.5 zip successfully
grafana_1     | 
grafana_1     | Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
grafana_1     | 
vwsfriend_1   | INFO:VWsFriend:vwsfriend 0.4.1 (using WeConnect-python 0.20.6)
vwsfriend_1   | INFO:weconnect:Could not use token from file /tmp/weconnect.token ([Errno 2] No such file or directory: '/tmp/weconnect.token')
grafana_1     | ✔ Downloaded pr0ps-trackmap-panel v2.1.2 zip successfully
grafana_1     | 
grafana_1     | Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
grafana_1     | 
grafana_1     | ✔ Downloaded natel-plotly-panel v0.0.7 zip successfully
grafana_1     | 
grafana_1     | Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
grafana_1     | 
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Starting Grafana" logger=server version=8.1.0 commit=62e720c06b branch=HEAD compiled=2021-08-05T12:49:59+0000
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_USER=root"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_USERS_ALLOW_SIGN_UP=false"
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="App mode production" logger=settings
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Starting DB migrations" logger=migrator
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=330 duration=1.194297ms
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana_1     | t=2021-09-08T12:32:20+0000 lvl=info msg="Registering plugin" logger=plugins id=input
vwsfriend_1   | INFO:weconnect:Token refreshed
vwsfriend_1   | INFO:VWsFriend:Starting database upgrade if necessary
postgresdb_1  | 2021-09-08 12:32:21.134 UTC [19] FATAL:  password authentication failed for user "root"
postgresdb_1  | 2021-09-08 12:32:21.134 UTC [19] DETAIL:  Role "root" does not exist.
postgresdb_1  |         Connection matched pg_hba.conf line 99: "host all all all md5"
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
vwsfriend_1   |     return fn()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
vwsfriend_1   |     return _ConnectionFairy._checkout(self)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
vwsfriend_1   |     fairy = _ConnectionRecord.checkout(pool)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
vwsfriend_1   |     rec = pool._do_get()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
vwsfriend_1   |     return self._create_connection()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
vwsfriend_1   |     return _ConnectionRecord(self)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
vwsfriend_1   |     self.__connect()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
vwsfriend_1   |     pool.logger.debug("Error on connect(): %s", e)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
vwsfriend_1   |     compat.raise_(
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
vwsfriend_1   |     raise exception
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
vwsfriend_1   |     connection = pool._invoke_creator(self)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
vwsfriend_1   |     return dialect.connect(*cargs, **cparams)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
vwsfriend_1   |     return self.dbapi.connect(*cargs, **cparams)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
vwsfriend_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
vwsfriend_1   | psycopg2.OperationalError: FATAL:  password authentication failed for user "root"
vwsfriend_1   | 
vwsfriend_1   | 
vwsfriend_1   | The above exception was the direct cause of the following exception:
vwsfriend_1   | 
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/bin/vwsfriend", line 8, in <module>
vwsfriend_1   |     sys.exit(main())
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/vwsfriend/vwsfriend.py", line 142, in main
vwsfriend_1   |     connector = AgentConnector(weConnect=weConnect, dbUrl=args.dbUrl, interval=args.interval, withDB=args.withDatabase, withABRP=args.withABRP,
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/vwsfriend/agent_connector.py", line 32, in __init__
vwsfriend_1   |     run_database_migrations(dsn=dbUrl)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/vwsfriend/model/migrations.py", line 18, in run_database_migrations
vwsfriend_1   |     upgrade(config, "head")
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
vwsfriend_1   |     script.run_env()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
vwsfriend_1   |     util.load_python_file(self.dir, "env.py")
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
vwsfriend_1   |     module = load_module_py(module_id, path)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
vwsfriend_1   |     spec.loader.exec_module(module)  # type: ignore
vwsfriend_1   |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
vwsfriend_1   |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/vwsfriend/model/vwsfriend-schema/env.py", line 76, in <module>
vwsfriend_1   |     run_migrations_online()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/vwsfriend/model/vwsfriend-schema/env.py", line 64, in run_migrations_online
vwsfriend_1   |     with connectable.connect() as connection:
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
vwsfriend_1   |     return self._connection_cls(self, close_with_result=close_with_result)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
vwsfriend_1   |     else engine.raw_connection()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
vwsfriend_1   |     return self._wrap_pool_connect(self.pool.connect, _connection)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
vwsfriend_1   |     Connection._handle_dbapi_exception_noconnection(
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2069, in _handle_dbapi_exception_noconnection
vwsfriend_1   |     util.raise_(
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
vwsfriend_1   |     raise exception
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
vwsfriend_1   |     return fn()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
vwsfriend_1   |     return _ConnectionFairy._checkout(self)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
vwsfriend_1   |     fairy = _ConnectionRecord.checkout(pool)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
vwsfriend_1   |     rec = pool._do_get()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
vwsfriend_1   |     return self._create_connection()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
vwsfriend_1   |     return _ConnectionRecord(self)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
vwsfriend_1   |     self.__connect()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
vwsfriend_1   |     pool.logger.debug("Error on connect(): %s", e)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
vwsfriend_1   |     compat.raise_(
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
vwsfriend_1   |     raise exception
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
vwsfriend_1   |     connection = pool._invoke_creator(self)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
vwsfriend_1   |     return dialect.connect(*cargs, **cparams)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
vwsfriend_1   |     return self.dbapi.connect(*cargs, **cparams)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
vwsfriend_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
vwsfriend_1   | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "root"
vwsfriend_1   | 
vwsfriend_1   | (Background on this error at: https://sqlalche.me/e/14/e3q8)
grafana_1     | t=2021-09-08T12:32:21+0000 lvl=info msg="Registering plugin" logger=plugins id=pr0ps-trackmap-panel
grafana_1     | t=2021-09-08T12:32:21+0000 lvl=info msg="Registering plugin" logger=plugins id=natel-discrete-panel
grafana_1     | t=2021-09-08T12:32:21+0000 lvl=info msg="Registering plugin" logger=plugins id=natel-plotly-panel
grafana_1     | t=2021-09-08T12:32:21+0000 lvl=info msg="Registering plugin" logger=plugins id=pierosavi-imageit-panel
grafana_1     | t=2021-09-08T12:32:21+0000 lvl=info msg="Live Push Gateway initialization" logger=live.push_http
grafana_1     | t=2021-09-08T12:32:21+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
vwsfriend_vwsfriend_1 exited with code 1
postgresdb_1  | 2021-09-08 12:32:27.990 UTC [27] FATAL:  role "root" does not exist
```

**Comment by runebakjacobsen** [comment]
It turns out the issue lies in that I have changed my .env variables since the first run. Closing this issue 👍
