### ISSUE TITLE
Cannot retrieve car data

### ISSUE THREAD

**Issue by mtbsteve** [tillsteinbach/VWsFriend#386]
I installed vwsfriend docker image on a Raspy. I can connect to the weconnect server, however it does not retrieve any car data.
I am running `docker-compose version 1.29.2`
And libseccomp2 is version 2.5.1
After executing docker-compose with my environment file, I get the following errors.
Any idea on how to resolve?

```
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/PIL/Image.py", line 3135, in open
vwsfriend_1   |     fp.seek(0)
vwsfriend_1   | io.UnsupportedOperation: seek
vwsfriend_1   | 
vwsfriend_1   | During handling of the above exception, another exception occurred:
vwsfriend_1   | 
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/usr/lib/python3.11/http/client.py", line 565, in _get_chunk_left
vwsfriend_1   |     chunk_left = self._read_next_chunk_size()
vwsfriend_1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/usr/lib/python3.11/http/client.py", line 532, in _read_next_chunk_size
vwsfriend_1   |     return int(line, 16)
vwsfriend_1   |            ^^^^^^^^^^^^^
vwsfriend_1   | ValueError: invalid literal for int() with base 16: b''
vwsfriend_1   | 
vwsfriend_1   | During handling of the above exception, another exception occurred:
vwsfriend_1   | 
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/usr/lib/python3.11/http/client.py", line 582, in _read_chunked
vwsfriend_1   |     chunk_left = self._get_chunk_left()
vwsfriend_1   |                  ^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/usr/lib/python3.11/http/client.py", line 567, in _get_chunk_left
vwsfriend_1   |     raise IncompleteRead(b'')
vwsfriend_1   | http.client.IncompleteRead: IncompleteRead(0 bytes read)
vwsfriend_1   | 
vwsfriend_1   | The above exception was the direct cause of the following exception:
vwsfriend_1   | 
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
vwsfriend_1   |     yield
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/urllib3/response.py", line 567, in read
vwsfriend_1   |     data = self._fp_read(amt) if not fp_closed else b""
vwsfriend_1   |            ^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/urllib3/response.py", line 533, in _fp_read
vwsfriend_1   |     return self._fp.read(amt) if amt is not None else self._fp.read()
vwsfriend_1   |                                                       ^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/usr/lib/python3.11/http/client.py", line 459, in read
vwsfriend_1   |     return self._read_chunked(amt)
vwsfriend_1   |            ^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/usr/lib/python3.11/http/client.py", line 597, in _read_chunked
vwsfriend_1   |     raise IncompleteRead(b''.join(value)) from exc
vwsfriend_1   | http.client.IncompleteRead: IncompleteRead(8972 bytes read)
vwsfriend_1   | 
vwsfriend_1   | During handling of the above exception, another exception occurred:
vwsfriend_1   | 
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/bin/vwsfriend", line 8, in <module>
vwsfriend_1   |     sys.exit(main())
vwsfriend_1   |              ^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/vwsfriend/vwsfriend_base.py", line 501, in main
vwsfriend_1   |     weConnect.update(updateCapabilities=True, updatePictures=True, force=True)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/weconnect.py", line 191, in update
vwsfriend_1   |     self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/weconnect.py", line 210, in updateVehicles
vwsfriend_1   |     vehicle = Vehicle(weConnect=self, vin=vin, parent=self.__vehicles, fromDict=vehicleDict, fixAPI=self.fixAPI,
vwsfriend_1   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 124, in __init__
vwsfriend_1   |     self.update(fromDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures, selective=selective)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 225, in update
vwsfriend_1   |     self.updatePictures()
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 395, in updatePictures
vwsfriend_1   |     img = Image.open(imageDownloadResponse.raw)
vwsfriend_1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/PIL/Image.py", line 3137, in open
vwsfriend_1   |     fp = io.BytesIO(fp.read())
vwsfriend_1   |                     ^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/urllib3/response.py", line 566, in read
vwsfriend_1   |     with self._error_catcher():
vwsfriend_1   |   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
vwsfriend_1   |     self.gen.throw(typ, value, traceback)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/urllib3/response.py", line 461, in _error_catcher
vwsfriend_1   |     raise ProtocolError("Connection broken: %r" % e, e)
vwsfriend_1   | urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(8972 bytes read)', IncompleteRead(8972 bytes read))
```

**Comment by tillsteinbach** [comment]
But currently there also seem to be some problems with the WeConnect Servers.

**Comment by thgau** [comment]
My WeConnect App could not connect for 4 hours. I restarted it and now it did sync but the UI looks a bit different. I also restarted vwsfriend and it is working again.

**Comment by tillsteinbach** [comment]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/3825852/211349091-43d896a6-013a-4f3d-b511-3e45bb4a00d8.png">
Yes, there is something going on...

**Comment by mtbsteve** [comment]
I am closing the issue at this point since it may be related to the ongoing changes on the backend.
