### ISSUE TITLE
Container crash when charging session started

### ISSUE THREAD

**Issue by amenychtas** [tillsteinbach/VWsFriend#393]
Today I noticed the the contaired was crashed and it probably related to a charging session that started. The car is ID.3 v3.0.

Here is the log:
```
2023-01-12T06:19:39+0000:INFO:vwsfriend_base:Updating data from WeConnect
Traceback (most recent call last):
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/vwsfriend_base.py", line 501, in main
    weConnect.update(updateCapabilities=True, updatePictures=True, force=True)
  File "/opt/venv/lib/python3.11/site-packages/weconnect/weconnect.py", line 193, in update
    self.updateComplete()
  File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 534, in updateComplete
    child.updateComplete()
  File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 534, in updateComplete
    child.updateComplete()
  File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 534, in updateComplete
    child.updateComplete()
  [Previous line repeated 3 more times]
  File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 97, in updateComplete
    observer(element=self, flags=self.onCompleteNotifyFlags)
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/agents/charge_agent.py", line 115, in __onChargingStateChange
    self.session.refresh(self.chargingSession)
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2350, in refresh
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Could not refresh instance '<ChargingSession at 0x7fc6ea326a90>'
```

And here are the last recorded events (GMT+2): 
![image](https://user-images.githubusercontent.com/3939897/212018804-f4641d8b-98fe-4f47-9a9a-be9d23f355b1.png)

**Comment by tillsteinbach** [comment]
I have seen that before, but until now I cannot reproduce the issue. This needs further investigation.

**Comment by tillsteinbach** [comment]
This looks like the postgres database was shutdown

**Comment by amenychtas** [comment]
I managed to recreate the issue either by starting / stoping charging from the charger side right after connecting the cable, or by connecting the cable and not starting the session from the charger. In the latter case a notification that "charging failed to start" is received in the WeConnect app.

Here is the log in v0.23.9:
```
Traceback (most recent call last):
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/vwsfriend_base.py", line 516, in main
    weConnect.update(updateCapabilities=True, updatePictures=True, force=True)
  File "/opt/venv/lib/python3.11/site-packages/weconnect/weconnect.py", line 195, in update
    self.updateComplete()
  File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 533, in updateComplete
    child.updateComplete()
  File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 533, in updateComplete
    child.updateComplete()
  File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 533, in updateComplete
    child.updateComplete()
  [Previous line repeated 3 more times]
  File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 96, in updateComplete
    observer(element=self, flags=self.onCompleteNotifyFlags)
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/agents/charge_agent.py", line 259, in __onPlugConnectionStateChange
    self.updatePosition()
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/agents/charge_agent.py", line 368, in updatePosition
    self.chargingSession.charger = chargerFromLatLonWithGeofence(weConnect=self.vehicle.weConnectVehicle.weConnect, session=self.session,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 528, in __set__
    self.impl.set(
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1453, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1496, in fire_replace_event
    state._modified_event(dict_, self, previous)
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 926, in _modified_event
    session._autobegin_t()
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1755, in _autobegin_t
    trans = SessionTransaction(
            ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 865, in __init__
    TransactionalContext._trans_ctx_check(session)
  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/util.py", line 110, in _trans_ctx_check
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Can't operate on closed transaction inside context manager.  Please complete the context manager before emitting further commands.
```

And here is the partially logged charging session:  
<img width="745" alt="image" src="https://user-images.githubusercontent.com/3939897/232332042-00f4a938-912c-4c6d-b075-1b8abe16e29b.png">

After this error, no data are logged and the container has to be restarted. Definitely postgres is working fine. I'm thinking that this may be the cause for the other data recording issues: #442 #317 #294

**Comment by blackmarlin4** [comment]
Same here. After 16 days of operation without any problem I get the following error with version 0.24.7:
Restarting the container helps in my case. This error occured every time after > 10 days of operation in my case.

`<html>
<body>

2024/11/26 16:19:05 | stderr | sqlalchemy.exc.InvalidRequestError: Can't operate on closed transaction inside context manager.  Please complete the context manager before emitting further commands.
-- | -- | --
2024/11/26 16:19:05 | stderr | raise exc.InvalidRequestError(
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 111, in _trans_ctx_check
2024/11/26 16:19:05 | stderr | TransactionalContext._trans_ctx_check(session)
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 931, in __init__
2024/11/26 16:19:05 | stderr | ^^^^^^^^^^^^^^^^^^^
2024/11/26 16:19:05 | stderr | trans = SessionTransaction(
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1877, in _autobegin_t
2024/11/26 16:19:05 | stderr | session._autobegin_t()
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 927, in _modified_event
2024/11/26 16:19:05 | stderr | state._modified_event(dict_, self, previous)
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1510, in fire_replace_event
2024/11/26 16:19:05 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/26 16:19:05 | stderr | value = self.fire_replace_event(state, dict_, value, old, initiator)
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1467, in set
2024/11/26 16:19:05 | stderr | self.impl.set(
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
2024/11/26 16:19:05 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/26 16:19:05 | stderr | self.chargingSession.charger = chargerFromLatLonWithGeofence(weConnect=self.vehicle.weConnectVehicle.weConnect, session=self.session,
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/vwsfriend/agents/charge_agent.py", line 385, in updatePosition
2024/11/26 16:19:05 | stderr | self.updatePosition()
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/vwsfriend/agents/charge_agent.py", line 329, in __onPlugLockStateChange
2024/11/26 16:19:05 | stderr | observer(element=self, flags=self.onCompleteNotifyFlags)
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 96, in updateComplete
2024/11/26 16:19:05 | stderr | [Previous line repeated 3 more times]
2024/11/26 16:19:05 | stderr | child.updateComplete()
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 533, in updateComplete
2024/11/26 16:19:05 | stderr | child.updateComplete()
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 533, in updateComplete
2024/11/26 16:19:05 | stderr | child.updateComplete()
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 533, in updateComplete
2024/11/26 16:19:05 | stderr | self.updateComplete()
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/weconnect/weconnect.py", line 197, in update
2024/11/26 16:19:05 | stderr | weConnect.update(updateCapabilities=True, updatePictures=True, force=True, selective=[Domain.ACCESS,
2024/11/26 16:19:05 | stderr | File "/opt/venv/lib/python3.12/site-packages/vwsfriend/vwsfriend_base.py", line 519, in main
2024/11/26 16:19:05 | stderr | ^^^^^^
2024/11/26 16:19:05 | stderr | sys.exit(main())
2024/11/26 16:19:05 | stderr | File "/opt/venv/bin/vwsfriend", line 8, in <module>
2024/11/26 16:19:05 | stderr | Traceback (most recent call last):


</body>
</html>`
