### ISSUE TITLE
Error during startup of vwsfriend container

### ISSUE THREAD

**Issue by unassal** [tillsteinbach/VWsFriend#434]
Hello - I have been running VWsFriend for a while but since an update a while back it doesn't really come up anymore. I had the suspicion that there is some issue with data from previous versions, so I did a `docker system prune --volumes` today to make sure that I start with a clean system.

However, that still didn't succeed. The container restarts endlessly and the log looks like this:

>> 
2023-02-25T17:49:27+0000:INFO:vwsfriend_base:vwsfriend 0.23.6 (using WeConnect-python 0.54.0, WeConnect-mqtt 0.42.1)
2023-02-25T17:49:27+0000:INFO:session_manager:Could not use token from file /tmp/weconnect.token ([Errno 2] No such file or directory: '/tmp/weconnect.token')
2023-02-25T17:49:29+0000:INFO:agent_connector:It looks like you have an existing database will check if an upgrade is necessary
2023-02-25T17:49:29+0000:INFO:migration:Context impl PostgresqlImpl.
2023-02-25T17:49:29+0000:INFO:migration:Will assume transactional DDL.
2023-02-25T17:49:29+0000:INFO:agent_connector:Database upgrade done
Traceback (most recent call last):
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/vwsfriend_base.py", line 476, in main
    ui.run(host=args.host, port=args.port)
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/ui/vwsfriend_ui.py", line 210, in run
    webthread.start()
  File "/usr/lib/python3.11/threading.py", line 957, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
>>

This is running on a Debian 10 linux vm (in proxmox). 

Does anyone have an idea how I could bring back the system into operational state?

**Comment by tillsteinbach** [comment]
Looks like some sort of Ressource limitation on the host. Did you try to restart everything?
