### ISSUE TITLE
No data recorded also with 0.23.7

### ISSUE THREAD

**Issue by oldgitdaddy** [tillsteinbach/VWsFriend#444]
Hi there,
I pulled the latest update, but still I do not get any update from my VW ID3. The data has not been recorded for some days. There is a huge time difference regarding update from the server and update from the car.
![image](https://user-images.githubusercontent.com/4282985/222547457-283b50e5-af45-4ded-b6fe-a6d751c5c4ea.png)

The logs do not show significant errors (login and all this seems to work), except for this one:

```
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/bin/vwsfriend", line 8, in <module>
vwsfriend_1   |     sys.exit(main())
vwsfriend_1   |              ^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/vwsfriend/vwsfriend_base.py", line 516, in main
vwsfriend_1   |     weConnect.update(updateCapabilities=True, updatePictures=True, force=True)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/weconnect.py", line 193, in update
vwsfriend_1   |     self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/weconnect.py", line 218, in updateVehicles
vwsfriend_1   |     self.__vehicles[vin].update(fromDict=vehicleDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures,
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 220, in update
vwsfriend_1   |     self.updateStatus(updateCapabilities=updateCapabilities, force=force, selective=selective)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 330, in updateStatus
vwsfriend_1   |     self.domains[domain.value][key].update(fromDict=data[domain.value][key])
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/climatization_timer.py", line 51, in update
vwsfriend_1   |     super().update(fromDict=fromDict, ignoreAttributes=(ignoreAttributes + ['timers', 'timeInCar']))
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/generic_status.py", line 106, in update
vwsfriend_1   |     newRequest = GenericStatus.Request(localAddress=key, parent=self.requests, fromDict=request)
vwsfriend_1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/generic_status.py", line 150, in __init__
vwsfriend_1   |     self.update(fromDict)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/elements/generic_status.py", line 155, in update
vwsfriend_1   |     self.operation.fromDict(fromDict, 'operation')
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/weconnect/addressable.py", line 317, in fromDict
vwsfriend_1   |     self.setValueWithCarTime(self.valueType.UNKNOWN, lastUpdateFromCar=None, fromServer=True)
vwsfriend_1   |                              ^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/usr/lib/python3.11/enum.py", line 787, in __getattr__
vwsfriend_1   |     raise AttributeError(name) from None
vwsfriend_1   | AttributeError: UNKNOWN
```
Installation is running on raspberry pi3.
Any hint or fix is appreciated. Thank you.

**Comment by tillsteinbach** [comment]
Please try 0.23.8. this should fix the error

**Comment by oldgitdaddy** [comment]
Thanks. Worked. Awesome! 😸
