### ISSUE TITLE
Unable to connect to VW servers.

### ISSUE THREAD

**Issue by danutsoare** [tillsteinbach/VWsFriend#449]
Hi. I've notice that my Grafana dashboard is not updated anymore.  One of the container is reporting the following error:
`onnect%3A%2F%2Fauthenticated&nonce=113443941326842120241678118434 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca7fafda90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/vwsfriend/vwsfriend_base.py", line 215, in main
    weConnect = weconnect.WeConnect(username=weConnectUsername, password=weConnectPassword, tokenfile=tokenfile,
  File "/opt/venv/lib/python3.9/site-packages/weconnect/weconnect.py", line 96, in __init__
    self.__session.login()
  File "/opt/venv/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 72, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/opt/venv/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 92, in authorizationUrl
    tryLoginResponse: requests.Response = self.get(authUrl, allow_redirects=False, access_type=AccessType.NONE)
  File "/opt/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 67, in request
    return super(WeConnectSession, self).request(
  File "/opt/venv/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 181, in request
    return super(OpenIDSession, self).request(
  File "/opt/venv/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.apps.emea.vwapps.io', port=443): Max retries exceeded with url: /authorize?redirect_uri=weconnect%3A%2F%2Fauthenticated&nonce=137900450304028803851678118496 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f174c2c9a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))` 
Is this a known VW issue or my docker images are old?
Thank you in advanced.

**Comment by tillsteinbach** [comment]
Did you update to the latest version?

**Comment by danutsoare** [comment]
Hi. Updating the containers solve my problem. Thank you!
