### ISSUE TITLE
PostgreSQL issue

### ISSUE THREAD

**Issue by Ezor** [tillsteinbach/VWsFriend#538]
Hello,

I have a problem with the postgresql database of vwsfriend since few weeks. When this problem occurs, vwsfriend is still updating data of the car, but grafana stops updating. Each time this problem occurs I have to restart vwsfriend.
Do you have any clue to fix this issue ?

Anyways, thanks for you for this great application.

Car : ID3, 3.2
Homekit enabled

```
vwsfriend_1   | 2023-09-02T14:37:51+0000:INFO:charging:Switch charging off
vwsfriend_1   | 2023-09-02T14:38:41+0000:INFO:charging:Switch charging off
vwsfriend_1   | 2023-09-02T14:39:31+0000:INFO:charging:Switch charging off
vwsfriend_1   | 2023-09-02T14:41:43+0000:INFO:charging:Switch charging on
vwsfriend_1   | 2023-09-02T14:55:13+0000:INFO:charging:Switch charging on
vwsfriend_1   | 2023-09-02T14:55:13+0000:INFO:openid_session:Token expired
vwsfriend_1   | 2023-09-02T14:55:13+0000:INFO:we_connect_session:Refreshing tokens
vwsfriend_1   | 2023-09-02T14:58:13+0000:INFO:charging:Switch charging on
vwsfriend_1   | 2023-09-02T15:23:31+0000:INFO:charging:Switch charging off
vwsfriend_1   | 2023-09-02T15:25:23+0000:INFO:charging:Switch charging on
vwsfriend_1   | 2023-09-02T16:09:32+0000:INFO:charging:Switch charging off
vwsfriend_1   | 2023-09-02T16:09:32+0000:INFO:openid_session:Token expired
vwsfriend_1   | 2023-09-02T16:09:32+0000:INFO:we_connect_session:Refreshing tokens
vwsfriend_1   | 2023-09-02T18:17:08+0000:ERROR:_internal:Error on request:
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
vwsfriend_1   |     self.dialect.do_execute(
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
vwsfriend_1   |     cursor.execute(statement, parameters)
vwsfriend_1   | psycopg2.OperationalError: server closed the connection unexpectedly
vwsfriend_1   | 	This probably means the server terminated abnormally
vwsfriend_1   | 	before or while processing the request.
vwsfriend_1   | 
vwsfriend_1   | 
vwsfriend_1   | The above exception was the direct cause of the following exception:
vwsfriend_1   | 
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 364, in run_wsgi
vwsfriend_1   |     execute(self.server.app)
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 325, in execute
vwsfriend_1   |     application_iter = app(environ, start_response)
vwsfriend_1   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
vwsfriend_1   |     return self.wsgi_app(environ, start_response)
vwsfriend_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
vwsfriend_1   |     response = self.handle_exception(e)
vwsfriend_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
vwsfriend_1   |     response = self.full_dispatch_request()
vwsfriend_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
vwsfriend_1   |     rv = self.handle_user_exception(e)
vwsfriend_1   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
vwsfriend_1   |     rv = self.preprocess_request()
vwsfriend_1   |          ^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
vwsfriend_1   |     rv = self.ensure_sync(before_func)()
vwsfriend_1   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/vwsfriend/ui/vwsfriend_ui.py", line 101, in before_request_callback
vwsfriend_1   |     flask.g.dbsettings = self.app.db.session.query(Settings).first()
vwsfriend_1   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2747, in first
vwsfriend_1   |     return self.limit(1)._iter().first()  # type: ignore
vwsfriend_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
vwsfriend_1   |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
vwsfriend_1   |                                                   ^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
vwsfriend_1   |     return self._execute_internal(
vwsfriend_1   |            ^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
vwsfriend_1   |     result: Result[Any] = compile_state_cls.orm_execute_statement(
vwsfriend_1   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
vwsfriend_1   |     result = conn.execute(
vwsfriend_1   |              ^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
vwsfriend_1   |     return meth(
vwsfriend_1   |            ^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
vwsfriend_1   |     return connection._execute_clauseelement(
vwsfriend_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
vwsfriend_1   |     ret = self._execute_context(
vwsfriend_1   |           ^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
vwsfriend_1   |     return self._exec_single_context(
vwsfriend_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
vwsfriend_1   |     self._handle_dbapi_exception(
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
vwsfriend_1   |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
vwsfriend_1   |     self.dialect.do_execute(
vwsfriend_1   |   File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
vwsfriend_1   |     cursor.execute(statement, parameters)
vwsfriend_1   | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
vwsfriend_1   | 	This probably means the server terminated abnormally
vwsfriend_1   | 	before or while processing the request.
vwsfriend_1   | 
vwsfriend_1   | [SQL: SELECT settings.id AS settings_id, settings.unit_of_length AS settings_unit_of_length, settings.unit_of_temperature AS settings_unit_of_temperature, settings.grafana_url AS settings_grafana_url, settings.vwsfriend_url AS settings_vwsfriend_url, settings.locale AS settings_locale 
vwsfriend_1   | FROM settings 
vwsfriend_1   |  LIMIT %(param_1)s]
vwsfriend_1   | [parameters: {'param_1': 1}]
vwsfriend_1   | (Background on this error at: https://sqlalche.me/e/20/e3q8)
vwsfriend_1   | 2023-09-02T18:42:48+0000:INFO:_internal:172.18.0.3 - - [02/Sep/2023 18:42:48] "GET /status/vehicles/<VIN>-status_or_car-badge.png.json HTTP/1.1" 200 -
vwsfriend_1   | 2023-09-02T18:42:52+0000:INFO:_internal:172.18.0.3 - - [02/Sep/2023 18:42:52] "GET /status/vehicles/<VIN>-status_or_car-badge.png.json HTTP/1.1" 200 -
vwsfriend_1   | 2023-09-02T18:43:05+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:05] "GET /settings/vehicle/database/<VIN> HTTP/1.1" 302 -
vwsfriend_1   | 2023-09-02T18:43:06+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:06] "GET /login?next=/settings/vehicle/database/<VIN> HTTP/1.1" 200 -
vwsfriend_1   | 2023-09-02T18:43:07+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:07] "GET /static/style.css HTTP/1.1" 304 -
vwsfriend_1   | 2023-09-02T18:43:11+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:11] "POST /login?next=/settings/vehicle/database/<VIN> HTTP/1.1" 302 -
vwsfriend_1   | 2023-09-02T18:43:14+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:14] "GET /settings/vehicle/database/<VIN> HTTP/1.1" 200 -
vwsfriend_1   | 2023-09-02T18:43:14+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:14] "POST /login?next=/settings/vehicle/database/<VIN> HTTP/1.1" 302 -
vwsfriend_1   | 2023-09-02T18:43:14+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:14] "GET /settings/vehicle/database/<VIN> HTTP/1.1" 200 -
vwsfriend_1   | 2023-09-02T18:43:14+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:14] "GET /static/style.css HTTP/1.1" 304 -
vwsfriend_1   | 2023-09-02T18:43:20+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:20] "GET /status/vehicles HTTP/1.1" 200 -
vwsfriend_1   | 2023-09-02T18:43:20+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:20] "GET /static/icons/settings.png HTTP/1.1" 304 -
vwsfriend_1   | 2023-09-02T18:43:20+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:20] "GET /static/style.css HTTP/1.1" 304 -
vwsfriend_1   | 2023-09-02T18:43:20+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:43:20] "GET /status/vehicles/<VIN>-car.png HTTP/1.1" 200 -
vwsfriend_1   | 2023-09-02T18:44:23+0000:INFO:_internal:172.18.0.3 - - [02/Sep/2023 18:44:23] "GET /status/vehicles/<VIN>-status_or_car-badge.png.json HTTP/1.1" 200 -
vwsfriend_1   | 2023-09-02T18:44:23+0000:INFO:_internal:192.168.0.33 - - [02/Sep/2023 18:44:23] "GET /status/vehicles/<VIN>-status_or_car-badge.png HTTP/1.1" 200 -
postgresdb_1  | 2023-09-02 18:45:41.114 UTC [72648] LOG:  could not send data to client: Broken pipe
postgresdb_1  | 2023-09-02 18:45:41.114 UTC [72648] FATAL:  connection to client lost
postgresdb_1  | 2023-09-02 18:45:41.539 UTC [1] LOG:  server process (PID 72647) was terminated by signal 13: Broken pipe
postgresdb_1  | 2023-09-02 18:45:41.539 UTC [1] LOG:  terminating any other active server processes
postgresdb_1  | 2023-09-02 18:45:41.541 UTC [72573] WARNING:  terminating connection because of crash of another server process
postgresdb_1  | 2023-09-02 18:45:41.541 UTC [72573] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
postgresdb_1  | 2023-09-02 18:45:41.541 UTC [72573] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgresdb_1  | 2023-09-02 18:45:41.542 UTC [72554] WARNING:  terminating connection because of crash of another server process
postgresdb_1  | 2023-09-02 18:45:41.542 UTC [72554] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
postgresdb_1  | 2023-09-02 18:45:41.542 UTC [72554] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgresdb_1  | 2023-09-02 18:45:41.543 UTC [72555] WARNING:  terminating connection because of crash of another server process
postgresdb_1  | 2023-09-02 18:45:41.543 UTC [72555] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
postgresdb_1  | 2023-09-02 18:45:41.543 UTC [72555] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgresdb_1  | 2023-09-02 18:45:41.545 UTC [71427] WARNING:  terminating connection because of crash of another server process
postgresdb_1  | 2023-09-02 18:45:41.545 UTC [71427] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
postgresdb_1  | 2023-09-02 18:45:41.545 UTC [71427] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgresdb_1  | 2023-09-02 18:45:41.548 UTC [71367] WARNING:  terminating connection because of crash of another server process
postgresdb_1  | 2023-09-02 18:45:41.548 UTC [71367] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
postgresdb_1  | 2023-09-02 18:45:41.548 UTC [71367] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgresdb_1  | 2023-09-02 18:45:41.555 UTC [72648] WARNING:  terminating connection because of crash of another server process
postgresdb_1  | 2023-09-02 18:45:41.555 UTC [72648] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
postgresdb_1  | 2023-09-02 18:45:41.555 UTC [72648] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgresdb_1  | 2023-09-02 18:45:42.546 UTC [1] LOG:  all server processes terminated; reinitializing
```

**Comment by Ezor** [comment]
Here is the log when restarting vwsfriend  :

```
postgresdb_1  | 
postgresdb_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgresdb_1  | 
postgresdb_1  | 2023-09-02 19:23:44.235 UTC [1] LOG:  starting PostgreSQL 13.12 (Debian 13.12-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgresdb_1  | 2023-09-02 19:23:44.262 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresdb_1  | 2023-09-02 19:23:44.262 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresdb_1  | 2023-09-02 19:23:45.257 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresdb_1  | 2023-09-02 19:23:46.191 UTC [14] LOG:  database system was shut down at 2023-09-02 19:23:09 UTC
postgresdb_1  | 2023-09-02 19:23:46.797 UTC [1] LOG:  database system is ready to accept connections
postgresdb_1  | 2023-09-02 19:24:29.338 UTC [1] LOG:  server process (PID 44) was terminated by signal 13: Broken pipe
postgresdb_1  | 2023-09-02 19:24:29.338 UTC [1] LOG:  terminating any other active server processes
postgresdb_1  | 2023-09-02 19:24:29.341 UTC [18] WARNING:  terminating connection because of crash of another server process
postgresdb_1  | 2023-09-02 19:24:29.341 UTC [18] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
postgresdb_1  | 2023-09-02 19:24:29.341 UTC [18] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgresdb_1  | 2023-09-02 19:24:29.360 UTC [45] WARNING:  terminating connection because of crash of another server process
postgresdb_1  | 2023-09-02 19:24:29.360 UTC [45] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
postgresdb_1  | 2023-09-02 19:24:29.360 UTC [45] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
postgresdb_1  | 2023-09-02 19:24:30.125 UTC [1] LOG:  all server processes terminated; reinitializing
postgresdb_1  | 2023-09-02 19:24:30.725 UTC [46] LOG:  database system was interrupted; last known up at 2023-09-02 19:23:46 UTC
grafana_1     | logger=context userId=1 orgId=1 uname=admin t=2023-09-02T19:24:33.297308154Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.0.121 time_ms=2046 duration=2.046578097s size=0 referer= handler=/api/live/ws
postgresdb_1  | 2023-09-02 19:24:34.436 UTC [54] FATAL:  the database system is in recovery mode
grafana_1     | logger=live t=2023-09-02T19:24:34.455950238Z level=info msg="Initialized channel handler" channel=grafana/dashboard/uid/b0WnuNMnk address=grafana/dashboard/uid/b0WnuNMnk
postgresdb_1  | 2023-09-02 19:24:34.553 UTC [46] LOG:  database system was not properly shut down; automatic recovery in progress
postgresdb_1  | 2023-09-02 19:24:35.608 UTC [46] LOG:  redo starts at 0/3EF8CE08
postgresdb_1  | 2023-09-02 19:24:35.608 UTC [46] LOG:  invalid record length at 0/3EF8CE40: wanted 24, got 0
postgresdb_1  | 2023-09-02 19:24:35.608 UTC [46] LOG:  redo done at 0/3EF8CE08
postgresdb_1  | 2023-09-02 19:24:38.806 UTC [1] LOG:  database system is ready to accept connections
```

After that, data of the car are up to date in vwsfriend and grafana. It works properly for few hours/days then the problem came back.

**Comment by tillsteinbach** [comment]
hmmm, this is strange. It looks like the connection to the database is somehow unstable

**Comment by Ezor** [comment]
I updated my ubuntu server and everything seems working perfectly. Thanks again for this app.
