### ISSUE TITLE
I can't upgrade past 0.23.11

### ISSUE THREAD

**Issue by ehsahog** [tillsteinbach/VWsFriend#618]
Hi,

I can't upgrade past 0.23.11. I have tried upgrading the normal way and also deploying new containers and doing a restore. It ends up the same. It tries to add battery_temperature to the database and fails. See log below.
Any ideas on how to fix this?

2024-03-11T20:45:52+0000:INFO:session_manager:Could not use token from file /tmp/weconnect.token ([Errno 2] No such file or directory: '/tmp/weconnect.token')
2024-03-11T20:45:55+0000:INFO:agent_connector:It looks like you have an existing database will check if an upgrade is necessary
2024-03-11T20:45:55+0000:INFO:migration:Context impl PostgresqlImpl.
2024-03-11T20:45:55+0000:INFO:migration:Will assume transactional DDL.
2024-03-11T20:45:55+0000:INFO:migration:Running upgrade f3a66cd08ebe -> 6c4cdc5006ba, Added battery temperature table
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateTable: relation "battery_temperature" already exists
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/vwsfriend_base.py", line 333, in main
    connector = AgentConnector(weConnect=weConnect, dbUrl=args.dbUrl, interval=args.interval, withDB=args.withDatabase, withABRP=args.withABRP,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/agent_connector.py", line 73, in __init__
    run_database_migrations(dsn=dbUrl)
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/model/migrations.py", line 21, in run_database_migrations
    upgrade(config, "head")
  File "/opt/venv/lib/python3.12/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/opt/venv/lib/python3.12/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/model/vwsfriend-schema/env.py", line 77, in <module>
    run_migrations_online()
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/model/vwsfriend-schema/env.py", line 71, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/model/vwsfriend-schema/versions/6c4cdc5006ba_added_battery_temperature_table.py", line 21, in upgrade
    op.create_table('battery_temperature',
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/opt/venv/lib/python3.12/site-packages/alembic/operations/ops.py", line 1311, in create_table
    return operations.invoke(op)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/alembic/operations/base.py", line 445, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/alembic/operations/toimpl.py", line 131, in create_table
    operations.impl.create_table(table)
  File "/opt/venv/lib/python3.12/site-packages/alembic/ddl/impl.py", line 366, in create_table
    self._exec(schema.CreateTable(table))
  File "/opt/venv/lib/python3.12/site-packages/alembic/ddl/impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
           ^^^^^
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1519, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "battery_temperature" already exists
[SQL: 
CREATE TABLE battery_temperature (
	id SERIAL NOT NULL, 
	vehicle_vin VARCHAR, 
	"carCapturedTimestamp" TIMESTAMP WITH TIME ZONE NOT NULL, 
	"temperatureHvBatteryMin_K" FLOAT, 
	"temperatureHvBatteryMax_K" FLOAT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(vehicle_vin) REFERENCES vehicles (vin), 
	UNIQUE (vehicle_vin, "carCapturedTimestamp")
)
]
(Background on this error at: https://sqlalche.me/e/20/f405)

**Comment by tillsteinbach** [comment]
That is strange, did you maybe add a battery_temperature table yourself by accident?

**Comment by ehsahog** [comment]
> That is strange, did you maybe add a battery_temperature table yourself by accident?

No, I did not. I had an issue with an upgrade earlier and had to revert back to 0.23.11. Maybe it failed after it added the table back then. However, I manually dropped the table in the database and the upgrade went ok it seems.
