### ISSUE TITLE
Unable to do a fresh install

### ISSUE THREAD

**Issue by ramonetdev** [tillsteinbach/VWsFriend#625]
Hi! My Raspberry decided to chrash a few days ago and when I try to reinstall VWsFriend I got a bunch of errors related to Docker. It´s possible that it could be related with de change of the version of Docker since v1 is deprecated (I couldn't install an older version in the Raspberry) and v2 seems to require some changes in the sentences. 
I asumethat the install process was made for v1 so I wonder if it could be possible to adapt it to v2, hoping that it would be enough to get VWFriend installed in my system again.

Many thanks in advance!

**Comment by tillsteinbach** [comment]
Can you post the errors here?

**Comment by ramonetdev** [comment]
There it is:

xxxx@raspberrypi:~/dockerconfig/vwfriends $ ls
docker-compose.yml  myconfig.env
xxxx@raspberrypi:~/dockerconfig/vwfriends $ docker-compose --env-file ./myconfig.env up
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

Thank you!

**Comment by tillsteinbach** [comment]
Can you try "docker compose" instead of "docker-compose"?

**Comment by ramonetdev** [comment]
It worked! Thank you Till!
