### ISSUE TITLE
 Insecure Transport for OAuth2 Authentication

### ISSUE THREAD

**Issue by motorto** [tillsteinbach/VWsFriend#702]
```
2024-11-30T16:02:48+0000:INFO:session_manager:Could not use token from file /tmp/weconnect.token ([Errno 2] No such file or directory: '/tmp/weconnect.token')
Traceback (most recent call last):
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/vwsfriend_base.py", line 329, in main
    weConnect = weconnect.WeConnect(username=weConnectUsername, password=weConnectPassword, spin=weConnectSpin, tokenfile=tokenfile,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/weconnect/weconnect.py", line 114, in __init__
    self.__session.login()
  File "/opt/venv/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
    afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 188, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

**Comment by thgau** [comment]
Same as #701 

Bitte einmal in der App ausloggen und wieder einloggen und die neuen Terms akzeptieren.

**Comment by kennyob** [comment]
> Same as #701
> 
> Bitte einmal in der App ausloggen und wieder einloggen und die neuen Terms akzeptieren.

This work for me. Thanks!

**Comment by kotipalvelu** [comment]
Please, could you elaborate a bit and if possible answer in english too. I have the same issue and I did not quite catch the comment.

**Comment by tillsteinbach** [comment]
Please logout and in in the Volkswagen app to accept the terms and conditions again.

**Comment by AndreasNoj** [comment]
Even after accept of new terms on login, still this error message.

**Comment by motorto** [comment]
Restarting the container doesn't help ?

**Comment by AndreasNoj** [comment]
No same issue - when loggin in on the app and on VW website, now always get the screen where I have to accept the "Term and Privacy"
<img width="375" alt="Screenshot 2024-12-06 102839" src="https://github.com/user-attachments/assets/8ee6057b-9411-419d-997b-e69bf74d447e">

**Comment by flav-allaz** [comment]
Same issue here. The website and app always ask me to accept the "Terms and Privacy" during the login process, even though I clicked "Accept" the last time I logged in.

![image](https://github.com/user-attachments/assets/7b23c773-8e27-47e2-a293-92bcd13e16a4)

**Comment by flav-allaz** [comment]
I was able to fix it by doing this trick on the [VW website](https://vwid.vwgroup.io/landing-page):
1. Change my country to Germany
2. Log out, then log in again and accept the "Terms and Privacy" (at this point "weconnect-cli" started working again)
3. Changed my country back to Switzerland
4. :partying_face: :tada:

**Comment by garethbradley** [comment]
I'm not able to change to Germany - the option is greyed out and only UK is available. 

Unable to start my vwsfriend container as a result (or at least it starts, but never presents a page)

**Comment by chaudron** [comment]
Same here, I can not change it from Netherlands to any other country.

**Comment by martintamke** [comment]
I was able to setup VWsFriend setting the country and region to "Germany". Logout of the VW website, log on again  and confirm the german terms and condition
![image](https://github.com/user-attachments/assets/3951feba-1d7a-417f-9505-fda6545d13c5)

**Comment by DieterKoblenz** [comment]
Unfortunately, even after changing the country (not the adress) and accepting the terms in the app, I am unable to start the container with the OAuth2 error.

**Comment by martintamke** [comment]
Can you post the response that you receive in the Terminal here? That would help  to see whether it is the same error others received.

**Comment by tillburner** [comment]
Hello,

since yesterday I also have the same problem. It seems that vwsfreind can't authorize with WeConnect.
I already logged out and in in the Volkswagen app.
I also tried on the Webpage https://vwid.vwgroup.io/.
I even changed the "country and region" to Albania and back to Germany, but there were no new "Terms and Privacy" notes for acceptance.

Maybe anybody could help?

Here is my docker error log:

```
vwsfriend-1   | 2025-11-25T11:50:39+0000:INFO:vwsfriend_base:vwsfriend 0.24.7 (using WeConnect-python 0.60.5, WeConnect-mqtt 0.49.2)
vwsfriend-1   | 2025-11-25T11:50:39+0000:INFO:session_manager:Could not use token from file /tmp/weconnect.token ([Errno 2] No such file or directory: '/tmp/weconnect.token')
vwsfriend-1   | Traceback (most recent call last):
vwsfriend-1   |   File "/opt/venv/bin/vwsfriend", line 8, in <module>
vwsfriend-1   |     sys.exit(main())
vwsfriend-1   |              ^^^^^^
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/vwsfriend/vwsfriend_base.py", line 329, in main
vwsfriend-1   |     weConnect = weconnect.WeConnect(username=weConnectUsername, password=weConnectPassword, spin=weConnectSpin, tokenfile=tokenfile,
vwsfriend-1   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/weconnect/weconnect.py", line 114, in __init__
vwsfriend-1   |     self.__session.login()
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
vwsfriend-1   |     response = self.doWebAuth(authorizationUrl)
vwsfriend-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 123, in doWebAuth
vwsfriend-1   |     loginFormResponse: requests.Response = websession.get(authorizationUrl, allow_redirects=False)
vwsfriend-1   |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
vwsfriend-1   |     return self.request("GET", url, **kwargs)
vwsfriend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
vwsfriend-1   |     prep = self.prepare_request(req)
vwsfriend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
vwsfriend-1   |     p.prepare(
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/requests/models.py", line 367, in prepare
vwsfriend-1   |     self.prepare_url(url, params)
vwsfriend-1   |   File "/opt/venv/lib/python3.12/site-packages/requests/models.py", line 438, in prepare_url
vwsfriend-1   |     raise MissingSchema(
vwsfriend-1   | requests.exceptions.MissingSchema: Invalid URL '/u/login?state=hKFo2SB6MkkyMmJBUW02bEJHQzhhYjduSF9UTFBEYzA2a18yd6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIGtmSndRNEpzMG9JVjVQZTdPQXpFYTd2T3Q4R3Y1RHppo2NpZNk2YTI0ZmJhNjMtMzRiMy00ZDQzLWIxODEtOTQyMTExZTZiZGE4QGFwcHNfdnctZGlsYWJfY29': No scheme supplied. Perhaps you meant https:///u/login?state=hKFo2SB6MkkyMmJBUW02bEJHQzhhYjduSF9UTFBEYzA2a18yd6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIGtmSndRNEpzMG9JVjVQZTdPQXpFYTd2T3Q4R3Y1RHppo2NpZNk2YTI0ZmJhNjMtMzRiMy00ZDQzLWIxODEtOTQyMTExZTZiZGE4QGFwcHNfdnctZGlsYWJfY29?
```

**Comment by ualex73** [comment]
@tillburner  most likely your issue is #752
