### ISSUE TITLE
Can't operate on closed transaction inside context manager.

### ISSUE THREAD

**Issue by dazzzl** [tillsteinbach/VWsFriend#708]
child.updateComplete()                                                                               
  [Previous line repeated 3 more times]                                            
  File "/home/daniel/.local/lib/python3.8/site-packages/weconnect/addressable.py", line 96, in updateComplete                                                                               
    observer(element=self, flags=self.onCompleteNotifyFlags)                                             
  File "/home/daniel/.local/lib/python3.8/site-packages/vwsfriend/agents/charge_agent.py", line 329, in __onPlugLockStateChange                                                                                   
    self.updatePosition()                                                          
  File "/home/daniel/.local/lib/python3.8/site-packages/vwsfriend/agents/charge_agent.py", line 385, in updatePosition                                                                      
    self.chargingSession.charger = chargerFromLatLonWithGeofence(weConnect=self.vehicle.weConnectVehicle.weConnect, session=self.session,                                                   
  File "/home/daniel/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__                                                                                 
    self.impl.set(                                                                                       
  File "/home/daniel/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1467, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)                                 
  File "/home/daniel/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1510, in fire_replace_event                                                                                           
    state._modified_event(dict_, self, previous)                                   
  File "/home/daniel/.local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 927, in _modified_event                                                                              
    session._autobegin_t()                                                                               
  File "/home/daniel/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1877, in _autobegin_t                                                                                                    
    trans = SessionTransaction(                                                    
  File "/home/daniel/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 931, in __init__
    TransactionalContext._trans_ctx_check(session)                                 
  File "/home/daniel/.local/lib/python3.8/site-packages/sqlalchemy/engine/util.py", line 111, in _trans_ctx_check                                                                           
    raise exc.InvalidRequestError(                                                                       
sqlalchemy.exc.InvalidRequestError: Can't operate on closed transaction inside context manager.  Please complete the context manager before emitting further commands.

**Comment by marcoinzaghi** [comment]
Same problem, almost every day.
To add more info, it seems the triggering problem is this - new status from the recent 3.7 car OTA update?

 2024-12-20T06:36:58+0000:WARNING:addressable:/vehicles/WVGZZZE2ZNP028945/domains/charging/chargingStatus/chargingScenario: **An unsupported chargingScenario: immediatelyOptimisedChargingFinished was provided, known values are [off, immediatelyChargingActive, immediatelyChargingFinished, chargingToDepartureTimeWaiting, chargingToDepartureTimeActive, optimisedChargingFinished, errorChargingSystem, unknown charging scenario] please report this as a bug**
Traceback (most recent call last):
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/vwsfriend_base.py", line 519, in main
    weConnect.update(updateCapabilities=True, updatePictures=True, force=True, selective=[Domain.ACCESS,
  File "/opt/venv/lib/python3.12/site-packages/weconnect/weconnect.py", line 197, in update
    self.updateComplete()
  File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 533, in updateComplete
    child.updateComplete()
  File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 533, in updateComplete
    child.updateComplete()
  File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 533, in updateComplete
    child.updateComplete()

**Comment by urosek** [comment]
I'm receiving the same issue. Any updates on this?

**Comment by oldgitdaddy** [comment]
I have looked into the code and I suppose it comes from nested transaction handling, also error suggests. @tillsteinbach: Can you please look at this, because it may stop a lot of instances, once charger is connected. ✌️
